version: "3.8"

services:
  mongodb:
    image: mongo:focal
    expose:
      - "27017"
    volumes:
      - db:/data/db

  backend:
    depends_on:
      - mongodb
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    environment:
      - DB_URL=mongodb://mongodb:27017/database
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/usr/backend/src
volumes:
  db:
